# FIXME. I want make the Makefile clear.
$(PROCFS-CONFIG)-objs:=proc.ko
$(PROCFS-CONFIG)-deps:=fat.o open.o read.o write.o dir.o ioctl.o close.o iname.o mount.o umount.o link.o
include $(WORKDIR)/Rule.make
